config/routes.rb
Rails.application.routes.draw do
  get 'team/show'
  get 'team/update'
  get 'rules', to: 'rules#index', as: 'rules'
  get 'welcome/index', as: "home"
  resources :teams, only: [:show] do
    resources :weeks, only: [:edit, :destroy]
  end
  resources :characters, only: [:index, :show]
  resources :points, only: [:create]

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :team
  has_many :points

  def full_name
    if self.last_name
      "#{self.first_name} #{self.last_name}"
    else
      self.first_name
    end
  end

  def get_occurance_of(week, type)
    self.points.where("week = #{week}").where("type = #{type}").count
  end

  def get_points_of(week, rule)
    self.points.where("week = #{week}").where("rule_id = #{rule.id}").map{|point| point.value}.reduce(0, :+)
  end
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :character
  belongs_to :team
  belongs_to :rule

  def value
    val = self.rule.points
  end

end

app/models/rule.rb
class Rule < ApplicationRecord
  has_many :points

  def points
    points = self.value
    points % 1 == 0 ? points.to_i : points
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :characters
  has_many :points

  def get_points(week)
    points = self.points.where("week = #{week}")
    accumulate_points(points)
  end

  def has_points?(week)
    self.points.where("week = #{week}").count > 0 ? true : false
  end

  def total_points
    points = self.points.all
    accumulate_points(points)
  end

  private
    #Takes an Active Record Collection of Points and returns
    #their accumulated value
    def accumulate_points(points)
      points.map{|point| point.value}.reduce(0, :+)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all.order(:first_name)
  end

  def show
    @character = Character.find(params[:id])
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def index
    @teams = Team.all
    @week = params[:week]
  end

  def create
    Point.create(point_params)
    redirect_to edit_team_week_path(params[:point][:team_id], params[:point][:week])
  end

  private
    def point_params
      params.require(:point).permit(:value, :week, :team_id, :character_id, :rule_id)
    end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index
    @rules = Rule.all
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team

  def show
   
  end

  def update
    
  end

  private
    def set_team
       @team = Team.find(params[:id])
    end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController

  def edit
    @team = Team.find(params[:team_id])
    @characters = @team.characters.order(:first_name)
    @week = params[:id]
    @rules = Rule.all
    @point = Point.new
  end

  def destroy
    @team = Team.find(params[:team_id])
    @week_number = params[:id]
    @point = @team.points.find_by(rule_id: params["rule-id"])
    if @point
      @point.destroy
    end
    redirect_to edit_team_week_path(@team.id, @week_number)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @teams = Team.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def season_length
    1..7
  end  
end

app/helpers/characters_helper.rb
module CharactersHelper
  def alive(character)
    if character.alive
      "alive"
    else
      "deceased"
    end
  end

  def get_point_by_week(week, point_id)

  end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def add_week_edit_icon(team, week)
    if team.has_points?(week)
      link_to team.get_points(week), edit_team_week_path(team.id, week)
    else
      link_to (fa_icon "edit").to_s, edit_team_week_path(team.id, week)
    end
  end
end

app/views/characters/index.html.erb
<h1>Characters</h1>
<ul>
  <% @characters.each do |character| %>
    <li>
      <%= link_to character.full_name, character_path(character.id) %>
    </li>
  <% end %>
</ul>

app/views/characters/show.html.erb
<h1><%= @character.full_name %></h1>
<ul>
  <li>
     On Team <%= @character.team.name %>
  </li>
  <li>
    Character is <%= alive(@character) %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Language" content="en">
    <title>Thronesss! | The Fantasy Football Version of GOT</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id="nav">
      <%= link_to "Home", home_path %>
      <%= link_to "Rules", rules_path %>
    </section>
    <section class="wrapper">
       <%= yield %>
    </section>
  </body>
</html>

app/views/points/_points_table_headers.html.erb
<td></td>
<td></td>
<th><div class="content">Character is Shown on Screen</div></th>
<th><div class="content">Character or their direwolf kills another drafted character</div></th>
<th><div class="content">Character or their direwolf kills an undrafted character</div></th>
<th><div class="content">Character kills a whitewalker</div></th>
<th><div class="content">Character kills a dragon</div></th>
<th><div class="content">Character dies</div></th>
<th><div class="content">Character is resurrected</div></th>
<th><div class="content">Character is resurrected as a whitewalker</div></th>
<th><div class="content">Character is shown onscreen as a whitewalker</div></th>
<th><div class="content">Character drinks alcohol</div></th>
<th><div class="content">Character has sex on screen</div></th>
<th><div class="content">Character has sex for the first time in GOT</div></th>
<th><div class="content">Character's direwolf is seen on screen</div></th>
<th><div class="content">Character sits on a throne</div></th>
<th><div class="content">Character has a vision/prophecy</div></th>
<th><div class="content">Savage of the week</div></th>

app/views/rules/index.html.erb
<section id="rules-container">
  <h1>Rules</h1>
<table>
  <tr>
    <th class="rule">Rule</th>
    <th class="points">Points</th>
  </tr>
  <% @rules.each do |rule| %>
    <tr>
      <td class="rule"> <%= rule.content %> </td>
      <td class="points"><%= rule.points %> per <%= rule.frequency %></td>
    </tr>
  <% end %>
</table>
<h2>Clarifications</h2>
<ul>
  <li>Gregor and Benjen are counted as alive (not whitewalkers). Any characters maintaining mental functions will be considered alive.</li>
  <li>If a character possesses another character and gets a kill, the possessing character gets the point (i.e. Bran gets points for killing through warging).</li>
  <li>All points will be ruled by Saumya. Rulings can be contested by vote, but overrulled if MORE than 50% vote against it. For a tie, Saumya's call goes.</li>
  <li>Pick order will be determined through a hat draw, and will be snaking (1, 2, 3, 4, 5, 5, 4, 3, 2, 1, etc).</li>
  <li>Points will be tallied by a different team member each week for a given person(i.e. Spencer will tally mine week 1, Thomas will tally mine week 2, etc).</li>
  <li>Only the total at the end of the season will count towards winning.</li>
  <li>Winnings will be distributed 75% / 20%.</li>
</ul>
</section>

app/views/weeks/_character_titles.html.erb
<tr>
  <th></th>
  <% @characters.each do |character| %>
    <th>
      <div class="content title">
        <%= character.full_name %>
      </div>
    </th>
  <% end %>
</tr>

app/views/weeks/_points_table_data.html.erb
<% @rules.each do |rule| %>
  <% if rule.value != 0 %>
    <tr>
      <td>
        <div class="left-col">
          <%= rule.content %> 
          (<%=pluralize(rule.points, "pt", "pts") %>)
        </div>
      </td>
      <% @characters.each do |character| %>
        <td class="<%= cycle("odd", "even") %>">
          <div class="content">
            <div class="side-by-side"><%= character.get_points_of(@week, rule) %></div>
            <div class="side-by-side close">
              <%= form_for @point do |f| %>
                <%= hidden_field_tag 'point[week]', @week %>
                <%= hidden_field_tag 'point[team_id]', @team.id %>
                <%= hidden_field_tag 'point[character_id]', character.id %>
                <%= hidden_field_tag 'point[rule_id]', rule.id %>
                <%= button_tag fa_icon("plus") %>
              <% end %>
            </div>
            <div class="side-by-side close red">
              <%= form_tag team_week_path(@team.id, @week), method: :delete do |f| %>
                <%= hidden_field_tag 'rule-id', rule.id %>
                <%= button_tag fa_icon "minus" %>
              <% end %>
            </div>
          </div>
        </td>
      <% end %>
    </tr>
  <% end %> 
<% end %>

app/views/weeks/edit.html.erb
<h1><%= @team.name %> Week <%= @week %></h1>
<table class="week-edit-table">
  <%= render "character_titles"  %>
  <%= render "points_table_data.html.erb" %>
</table>

app/views/welcome/_main_title.html.erb
<section id="main-title-container">
  <h1 id=main-title>Thronesss!</h1>
  <h2 id="subtitle">The Fantasy Football Version of GOT</h2>
</section>

app/views/welcome/_scores_table_data.html.erb
<% @teams.each do |team| %>
  <tr class="<%= cycle("odd", "even") %>">
    <td>
      <div class="welcome-table-left-col">
        <a href=<%= team_path(team.id) %>> <%= team.name %> </a>
      </div>
    </td>
    <% season_length.each do |week| %>
      <td class="points-col">
        <%= add_week_edit_icon(team, week) %>
      </td>
    <% end %>
    <td></td>
    <td>
      <strong> <%= team.total_points %> </strong> 
    </td>
  </tr>
<% end %>

app/views/welcome/_week_headers.html.erb
<tr>
  <th class="team-col">Team</th>
  <% season_length.each do |week| %>
    <th class="points-col">
      <%= "Week #{week}" %>
    </th>
  <% end %>
  <th id="table-spacer"></th>
  <th class="points-col">Total</th>
</tr>

app/views/welcome/index.html.erb
<section id="welcome-container">
  <%= render "main_title" %>
<table>
  <%= render "week_headers"  %>
  <%= render "scores_table_data" %>
</table>
</section>